services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://db:27017/stream-test
    expose:
      - "3000"
    depends_on:
      - db

  db:
    image: mongo:8.0
    container_name: mongo
    volumes:
      - stream-test-db:/data/db
    ports:
      - "27017:27017"

volumes:
  stream-test-db: